[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lattice_quantizer"
version = "0.0.1"
dependencies = ["numpy", "numba", "tqdm"]
requires-python = ">=3.8"

[tool.ruff]
# ignore E741
ignore = ["E741"]
